version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: forum_postgres
    restart: always
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_pass
      POSTGRES_DB: forum_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: forum_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@forum.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
